[QOL-8612] update ckanext-s3filestore to fix migration of legacy resources
qld-gov-au/ckan-qld-infrastructure pull request #210
Opened 2022-04-06 05:58 UTC by ThrawnCA

Since this only alters the version numbers for environments above DEV, merging it to 'develop' makes no difference.

2022-04-06 06:48 UTC, RossWebsterWork approved these changes

2022-04-06 07:20 UTC, RossWebsterWork requested changes
Not all checks were successful

2022-04-06 22:43 UTC, ThrawnCA commented
> Not all checks were successful

Yeah, that's a frequent but inconsistent error in the QA scenario tests. I haven't been able to track it down, and the fact that it produces blank screenshots (literally, zero-byte files) doesn't help. Just re-running the tests typically resolves it, but if someone has any insights, I'd love to resolve it.

2022-04-07 00:37 UTC, RossWebsterWork approved these changes

2022-04-07 01:03 UTC, merged