QOLDEV-1068 Security group cleanup
qld-gov-au/ckan-qld-infrastructure pull request #629
Opened 2024-12-23 03:09 UTC by ThrawnCA

Drop surplus web security groups as we have a 2-tier architecture, not 3.

2025-03-03 03:38 UTC, duttonw commented on templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
> -  LoadBalancerSG:
what is the reason for this change?

2025-03-03 03:53 UTC, ThrawnCA commented on templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
> -  LoadBalancerSG:
Reverting to the existing name.

2025-03-31 04:03 UTC, zmacca requested changes
Looks good, but there are conflicts due to my work fixing the security groups template being too large. The changes here make my fixes redundant, so you could revert my changes to eliminate the conflicts (in the develop branch, that would be reverting up to and including commit ad7743ea0ff0fb8e5a38f867581d54ae7befadc6).

2025-03-31 06:00 UTC, duttonw approved these changes

2025-03-31 06:31 UTC, merged